# Generated by Django 4.2.17 on 2025-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollappdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
